// Quill-Figma/src/app/components/StoryListView.tsx
import { Download, Trash2, FolderOpen, Settings, Feather, Wifi, WifiOff, AlertCircle, Plus } from 'lucide-react';
import type { Story, LLMSettings } from '../types';

const GENRE_COLORS: Record<string, string> = {
  Romance: 'text-rose-400 bg-rose-400/10 border-rose-400/20',
  'Dark Romance': 'text-purple-400 bg-purple-400/10 border-purple-400/20',
  Fantasy: 'text-blue-400 bg-blue-400/10 border-blue-400/20',
  Thriller: 'text-orange-400 bg-orange-400/10 border-orange-400/20',
  Angst: 'text-slate-400 bg-slate-400/10 border-slate-400/20',
  'Hurt/Comfort': 'text-pink-400 bg-pink-400/10 border-pink-400/20',
  'Slice of Life': 'text-green-400 bg-green-400/10 border-green-400/20',
  Action: 'text-yellow-400 bg-yellow-400/10 border-yellow-400/20',
  Horror: 'text-red-400 bg-red-400/10 border-red-400/20',
  Mystery: 'text-cyan-400 bg-cyan-400/10 border-cyan-400/20',
  'General Fiction': 'text-gray-400 bg-gray-400/10 border-gray-400/20',
};

function getGenreColor(genre: string) {
  return GENRE_COLORS[genre] ?? 'text-[#72708a] bg-white/5 border-white/10';
}

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function LLMStatusBadge({ settings, onClick }: { settings: LLMSettings; onClick: () => void }) {
  const configured = !!(settings.apiUrl && settings.model);
  return (
    <button
      onClick={onClick}
      className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs border transition-all ${
        configured
          ? 'text-emerald-400 bg-emerald-400/8 border-emerald-400/20 hover:bg-emerald-400/14'
          : 'text-[#72708a] bg-white/4 border-white/8 hover:border-white/14'
      }`}
    >
      {configured ? (
        <>
          <span className="relative flex h-1.5 w-1.5">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-60" />
            <span className="relative inline-flex rounded-full h-1.5 w-1.5 bg-emerald-400" />
          </span>
          <Wifi size={11} />
          LLM: Online
        </>
      ) : (
        <>
          <WifiOff size={11} />
          LLM: Not Configured
        </>
      )}
    </button>
  );
}

function StoryCard({
  story,
  onClick,
  onExport,
  onDelete,
}: {
  story: Story;
  onClick: () => void;
  onExport: (e: React.MouseEvent) => void;
  onDelete: (e: React.MouseEvent) => void;
}) {
  const wordCount = story.segments
    .filter(s => s.type === 'narrative')
    .reduce((n, s) => n + s.content.split(/\s+/).length, 0);

  return (
    <button
      onClick={onClick}
      className="group relative w-full text-left p-4 rounded-2xl bg-[#131318] border border-white/6 hover:border-[#c8922a]/30 hover:bg-[#17171e] transition-all duration-200 overflow-hidden"
    >
      {/* Top amber shimmer on hover */}
      <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[#c8922a]/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />

      <div className="flex items-start justify-between gap-2 mb-3">
        <h3
          className="text-[#e6e0d4] leading-snug line-clamp-2 pr-1"
          style={{ fontFamily: "'EB Garamond', serif", fontSize: '1.05rem' }}
        >
          {story.title}
        </h3>
        {story.segments.length === 0 && (
          <span className="shrink-0 text-[10px] text-[#72708a] bg-white/4 border border-white/8 px-2 py-0.5 rounded-full mt-0.5">
            Empty
          </span>
        )}
      </div>

      <div className="flex flex-wrap gap-1.5 mb-3">
        {story.genres.slice(0, 3).map(g => (
          <span key={g} className={`text-[10px] px-2 py-0.5 rounded-full border ${getGenreColor(g)}`}>
            {g}
          </span>
        ))}
      </div>

      <div className="flex items-center justify-between text-[11px] text-[#72708a]">
        <span>{story.pacing}</span>
        <div className="flex items-center gap-2">
          {wordCount > 0 && <span>{wordCount.toLocaleString()} words</span>}
          <span>{formatDate(story.updatedAt)}</span>
        </div>
      </div>

      {/* Card action buttons — revealed on hover */}
      <div className="absolute top-3 right-3 flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
        <button
          onClick={onExport}
          className="p-1.5 rounded-lg bg-[#1c1c24] border border-white/8 text-[#72708a] hover:text-[#e6e0d4] hover:border-white/16 transition-colors"
          title="Export story"
        >
          <Download size={12} />
        </button>
        <button
          onClick={onDelete}
          className="p-1.5 rounded-lg bg-[#1c1c24] border border-white/8 text-[#72708a] hover:text-red-400 hover:border-red-400/25 transition-colors"
          title="Delete story"
        >
          <Trash2 size={12} />
        </button>
      </div>
    </button>
  );
}

interface StoryListViewProps {
  stories: Story[];
  llmSettings: LLMSettings;
  onOpenStory: (id: string) => void;
  onNewStory: () => void;
  onImport: () => void;
  onLLMSettings: () => void;
  onExportStory: (story: Story) => void;
  onDeleteStory: (id: string) => void;
}

export function StoryListView({
  stories,
  llmSettings,
  onOpenStory,
  onNewStory,
  onImport,
  onLLMSettings,
  onExportStory,
  onDeleteStory,
}: StoryListViewProps) {
  return (
    <div className="min-h-screen bg-[#0c0c11] flex flex-col">
      {/* Header */}
      <header className="sticky top-0 z-10 px-4 pt-safe-top">
        <div className="flex items-center justify-between py-4 max-w-2xl mx-auto w-full">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-[#c8922a]/15 border border-[#c8922a]/30 flex items-center justify-center">
              <Feather size={15} className="text-[#c8922a]" />
            </div>
            <div>
              <div className="text-[#e6e0d4] leading-none" style={{ fontFamily: "'EB Garamond', serif", fontSize: '1.2rem' }}>
                Quill
              </div>
              <div className="text-[10px] text-[#72708a] leading-none mt-0.5">fanfic co-writing studio</div>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={onImport}
              className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-[#72708a] hover:text-[#e6e0d4] hover:bg-white/6 transition-colors text-xs"
              title="Import story"
            >
              <FolderOpen size={15} />
              <span className="hidden sm:inline">Import</span>
            </button>
            <button
              onClick={onLLMSettings}
              className="p-2 rounded-lg text-[#72708a] hover:text-[#e6e0d4] hover:bg-white/6 transition-colors"
              title="API settings"
            >
              <Settings size={17} />
            </button>
          </div>
        </div>
      </header>

      {/* LLM status */}
      <div className="px-4 max-w-2xl mx-auto w-full mb-5">
        <div className="flex items-center gap-3">
          <LLMStatusBadge settings={llmSettings} onClick={onLLMSettings} />
          {!llmSettings.apiUrl && (
            <span className="text-[11px] text-[#72708a]/70 flex items-center gap-1">
              <AlertCircle size={10} /> Configure to enable AI writing
            </span>
          )}
        </div>
      </div>

      {/* Content */}
      <main className="flex-1 px-4 pb-24 max-w-2xl mx-auto w-full">
        {stories.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 text-center">
            <div className="w-16 h-16 rounded-2xl bg-[#1c1c24] border border-white/6 flex items-center justify-center mb-5">
              <Feather size={28} className="text-[#c8922a]/50" />
            </div>
            <p className="text-[#e6e0d4] mb-1" style={{ fontFamily: "'EB Garamond', serif", fontSize: '1.3rem' }}>
              Your stories await
            </p>
            <p className="text-sm text-[#72708a] mb-8 max-w-xs">
              Begin a new story and let the words flow. Quill will help you shape every twist and turn.
            </p>
            <button
              onClick={onNewStory}
              className="flex items-center gap-2 px-6 py-3 rounded-xl bg-[#c8922a] hover:bg-[#d4a853] text-[#0c0c11] transition-colors"
            >
              <Plus size={16} />
              Start Your First Story
            </button>
          </div>
        ) : (
          <>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-xs text-[#72708a] uppercase tracking-wider">
                {stories.length} {stories.length === 1 ? 'Story' : 'Stories'}
              </h2>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {stories.map(story => (
                <StoryCard
                  key={story.id}
                  story={story}
                  onClick={() => onOpenStory(story.id)}
                  onExport={e => { e.stopPropagation(); onExportStory(story); }}
                  onDelete={e => { e.stopPropagation(); onDeleteStory(story.id); }}
                />
              ))}
            </div>
          </>
        )}
      </main>

      {/* FAB */}
      <button
        onClick={onNewStory}
        className="fixed bottom-6 right-4 sm:bottom-8 sm:right-8 w-14 h-14 rounded-2xl bg-[#c8922a] hover:bg-[#d4a853] text-[#0c0c11] shadow-lg shadow-[#c8922a]/20 flex items-center justify-center transition-all hover:scale-105 active:scale-95 z-20"
        aria-label="New story"
      >
        <Plus size={22} />
      </button>
    </div>
  );
}

// src/lib/components/StoryListView.svelte
<script lang="ts">
	import type { StoryMetadata } from '$lib/services/db';
	import type { AppConfig } from '$lib/services/db';
	import * as api from '$lib/services/api';
	import * as db from '$lib/services/db';
	import StoryCard from './StoryCard.svelte';
	import NewStoryModal from './NewStoryModal.svelte';
	import { connectionStatus } from '$lib/stores';
	import { Feather, FolderOpen, Settings, Plus, Wifi, WifiOff, AlertCircle } from '@lucide/svelte';

	let {
		onopen,
		onnewstory,
		onimport,
		onsettings
	}: {
		onopen: (id: string) => void;
		onnewstory: () => void;
		onimport: () => void;
		onsettings: () => void;
	} = $props();

	let stories = $state<StoryMetadata[]>([]);
	let config = $state<AppConfig | null>(null);
	let editingStory = $state<StoryMetadata | null>(null);

	let llmConfigured = $derived(!!config?.apiEntries?.length);
	let hasOnlineEntry = $derived(
		config?.apiEntries?.some(
			(e: AppConfig['apiEntries'][number]) =>
				e.capabilities?.text && ($connectionStatus[e.id] ?? false)
		) ?? false
	);

	async function load() {
		stories = await api.listStories();
		config = await api.getConfig();
	}

	$effect(() => {
		load();
	});

	function handleEdit(story: StoryMetadata) {
		editingStory = story;
	}

	function handleSaved() {
		editingStory = null;
		load();
	}

	function handleExport(story: StoryMetadata) {
		db.exportStory(story.id);
	}

	async function handleDelete(id: string) {
		if (!confirm('Delete this story? This cannot be undone.')) return;
		await api.deleteStory(id);
		stories = stories.filter((s) => s.id !== id);
	}
</script>

{#if editingStory}
	<NewStoryModal
		initialData={editingStory}
		oncreated={() => {}}
		onsaved={handleSaved}
		onclose={() => (editingStory = null)}
	/>
{/if}

<div class="min-h-dvh bg-background flex flex-col">
	<header class="sticky top-0 z-10 px-4">
		<div class="flex items-center justify-between py-4 max-w-2xl mx-auto w-full">
			<div class="flex items-center gap-2.5">
				<div
					class="w-8 h-8 rounded-xl bg-primary/15 border border-primary/30 flex items-center justify-center"
				>
					<Feather size={15} class="text-primary" />
				</div>
				<div>
					<div class="text-foreground leading-none font-serif text-xl">Quill</div>
					<div class="text-[10px] text-muted-foreground leading-none mt-0.5">
						fanfic co-writing studio
					</div>
				</div>
			</div>
			<div class="flex items-center gap-2">
				<button
					onclick={onimport}
					class="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-muted-foreground hover:text-foreground hover:bg-white/6 transition-colors text-xs"
					title="Import story"
				>
					<FolderOpen size={15} />
					<span class="hidden sm:inline">Import</span>
				</button>
				<button
					onclick={onsettings}
					class="p-2 rounded-lg text-muted-foreground hover:text-foreground hover:bg-white/6 transition-colors"
					title="API settings"
				>
					<Settings size={17} />
				</button>
			</div>
		</div>
	</header>

	<div class="px-4 max-w-2xl mx-auto w-full mb-5">
		<div class="flex items-center gap-3">
			<button
				onclick={onsettings}
				class="flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs border transition-all
					{hasOnlineEntry
					? 'text-emerald-400 bg-emerald-400/8 border-emerald-400/20 hover:bg-emerald-400/14'
					: llmConfigured
						? 'text-amber-400 bg-amber-400/8 border-amber-400/20 hover:bg-amber-400/14'
						: 'text-muted-foreground bg-white/4 border-white/8 hover:border-white/14'}"
			>
				{#if hasOnlineEntry}
					<span class="relative flex h-1.5 w-1.5">
						<span
							class="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-60"
						></span>
						<span class="relative inline-flex rounded-full h-1.5 w-1.5 bg-emerald-400"></span>
					</span>
					<Wifi size={11} />
					LLM: Online
				{:else if llmConfigured}
					<WifiOff size={11} />
					LLM: Unreachable
				{:else}
					<WifiOff size={11} />
					LLM: Not Configured
				{/if}
			</button>
			{#if !llmConfigured}
				<span class="text-[11px] text-muted-foreground/70 flex items-center gap-1">
					<AlertCircle size={10} /> Configure to enable AI writing
				</span>
			{/if}
		</div>
	</div>

	<main class="flex-1 px-4 pb-24 max-w-2xl mx-auto w-full">
		{#if stories.length === 0}
			<div class="flex flex-col items-center justify-center py-20 text-center">
				<div
					class="w-16 h-16 rounded-2xl bg-secondary border border-border flex items-center justify-center mb-5"
				>
					<Feather size={28} class="text-primary/50" />
				</div>
				<p class="text-foreground mb-1 font-serif text-xl">Your stories await</p>
				<p class="text-sm text-muted-foreground mb-8 max-w-xs">
					Begin a new story and let the words flow. Quill will help you shape every twist and turn.
				</p>
				<button
					onclick={onnewstory}
					class="flex items-center gap-2 px-6 py-3 rounded-xl bg-primary hover:bg-[#d4a853] text-primary-foreground transition-colors"
				>
					<Plus size={16} />
					Start Your First Story
				</button>
			</div>
		{:else}
			<div class="flex items-center justify-between mb-4">
				<h2 class="text-xs text-muted-foreground uppercase tracking-wider">
					{stories.length}
					{stories.length === 1 ? 'Story' : 'Stories'}
				</h2>
			</div>
			<div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
				{#each stories as story (story.id)}
					<StoryCard
						{story}
						onclick={() => onopen(story.id)}
						onedit={() => handleEdit(story)}
						onexport={() => handleExport(story)}
						ondelete={() => handleDelete(story.id)}
					/>
				{/each}
			</div>
		{/if}
	</main>

	<button
		onclick={onnewstory}
		class="fixed bottom-6 right-4 sm:bottom-8 sm:right-8 w-14 h-14 rounded-2xl bg-primary hover:bg-[#d4a853] text-primary-foreground shadow-lg shadow-primary/20 flex items-center justify-center transition-all hover:scale-105 active:scale-95 z-20"
		style="bottom: max(1.5rem, env(safe-area-inset-bottom, 1.5rem))"
		aria-label="New story"
	>
		<Plus size={22} />
	</button>
</div>
